### ISSUE TITLE
Add Kairos to managed launch services

### ISSUE THREAD

**Issue by pistachiomatt** [ilmoi/awesome-solana-nfts#31]
[Kairos](https://kairos.art) is the latest managed launch service to premiere on Solana. This one particularly focuses on UX and ease-of-use. Perhaps worth listing.

(For full disclosure, I'm one of the founders of Kairos. Happy to chat offline if you'd like proof/DOXing/or a legitimacy walkthrough.)

**Comment by ilmoi** [comment]
looks cool, just do a PR ser
