### ISSUE TITLE
Tool NFT solana

### ISSUE THREAD

**Issue by dranduil** [ilmoi/awesome-solana-nfts#41]

**Comment by ProAndry** [comment]
📅 Upcoming NFT Drops website [https://nextnftmint.com]
Rarity website [https://nextnftmint.com]

## 📅 Upcoming NFT Drops

[https://nextnftmint.com] - Never Miss NFT Projects Again! Top Upcoming NFT Drops in Web3.

## Rarity [https://nextnftmint.com] - Rarity checker. The best Gems are here!
